{"name": "test_ZB_NP_12", "status": "broken", "statusDetails": {"message": "ValueError: {'code': -32000, 'message': 'the tx data is invalid: the func is not exist'}", "trace": "new_validator_client = <tests.lib.client.Client object at 0x00000269F6EEE0B8>\n\n    def test_ZB_NP_12(new_validator_client):\n        new_validator_client.node.stop()\n        economic = new_validator_client.economic\n        node = economic.env.get_consensus_node_by_index(0)\n    \n        pri = economic.env.account.find_pri_key(new_validator_client.staking_address)\n        node.ppos.withdrewStaking(new_validator_client.node.node_id, pri)\n    \n        initial_validator, slashing_node_list = gen_validator_list(economic.env.consensus_node_id_list(), new_validator_client.node.node_id)\n    \n>       set_slashing(initial_validator, slashing_node_list, node, economic, \"1\")\n\neconomic   = <tests.lib.economic.Economic object at 0x00000269F6EEE908>\ninitial_validator = ['488fb1c783f7ac6a20d320e8442ddebe8cf983f5eda7effd00b919afdcf31dcd10e6b2bcee158245fef3a587e0248bea8cf8f6905af833623d03...b2046a77afb48a13f875c17d674421eda9c5345c32d9378490326d628e9f9b60392fcf7832ba82c9ebf5953573d6f93878c24f77e9cb53ee59fec']\nnew_validator_client = <tests.lib.client.Client object at 0x00000269F6EEE0B8>\nnode       = <environment.node.Node object at 0x00000269F51BE9B0>\npri        = 'c058198df2ebabf6c6ce035fa130614c5e91c305b782fea9880c34b96cc2ccd8'\nslashing_node_list = ['cfdf43591661d0107b7389a0ef68a2681cdf67d93183e36201acb631920cee349d4c6d7e8557602e101df0fe6b2e6808c66e0a27a2942096348f...0a9bf5bf7c6f5fb2abbeea3546d6557cec02992f7753f99c2e39f87fdbdb6280d7fc8a243518ef27834e55eb03ad6d8ef2f627b8f0001ee185300']\n\ntests\\ppos\\test_slashing_zero.py:144: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\ppos\\test_slashing_zero.py:58: in set_slashing\n    assert_set_validator_list(node, do[state])\ntests\\ppos\\test_slashing_zero.py:28: in assert_set_validator_list\n    result = node.debug.setValidatorList(validator_list, pri_key)\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\debug.py:22: in setValidatorList\n    return send_obj_transaction(self, data, self.web3.stakingAddress, pri_key, transaction_cfg)\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\utils\\transactions.py:72: in send_obj_transaction\n    tx_hash = HexBytes(obj.web3.platon.sendRawTransaction(signed_data)).hex()\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\eth.py:300: in sendRawTransaction\n    [raw_transaction],\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <client_sdk_python.manager.RequestManager object at 0x00000269F6EE9240>, method = 'platon_sendRawTransaction'\nparams = [HexBytes('0xf9017c028405f5e1008303345094100000000000000000000000000000000000000280b90115f901128382076cb9010bf90108b84...70ef30ce8f53a2469599c87d04b165fe10269e6dfd18c1157ca036f0c0a679be32cb58d7767c69d23d6675fa549cf59045c87d0bd4f3aa93915d')]\n\n    def request_blocking(self, method, params):\n        \"\"\"\n        Make a synchronous request using the provider\n        \"\"\"\n        response = self._make_request(method, params)\n    \n        if \"error\" in response:\n>           raise ValueError(response[\"error\"])\nE           ValueError: {'code': -32000, 'message': 'the tx data is invalid: the func is not exist'}\n\nmethod     = 'platon_sendRawTransaction'\nparams     = [HexBytes('0xf9017c028405f5e1008303345094100000000000000000000000000000000000000280b90115f901128382076cb9010bf90108b84...70ef30ce8f53a2469599c87d04b165fe10269e6dfd18c1157ca036f0c0a679be32cb58d7767c69d23d6675fa549cf59045c87d0bd4f3aa93915d')]\nresponse   = {'error': {'code': -32000, 'message': 'the tx data is invalid: the func is not exist'}, 'id': 3, 'jsonrpc': '2.0'}\nself       = <client_sdk_python.manager.RequestManager object at 0x00000269F6EE9240>\n\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\manager.py:112: ValueError"}, "attachments": [{"name": "env log", "source": "9aac6b64-058d-4985-a5d5-11d029dde76c-attachment.uri", "type": "text/uri-list"}, {"name": "env status", "source": "0b7056d3-4c93-4266-816b-4053d0d943d5-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "57321b49-f791-404b-bc5a-246ec63d8d37-attachment.txt", "type": "text/plain"}], "start": 1586652593896, "stop": 1586652596183, "uuid": "00abeeee-01bf-45c7-af10-1ba7b9eddeb1", "historyId": "3ea36a17405068789e106f98d6c35941", "testCaseId": "ff5a205ffb68062280e00537fa7ac56b", "fullName": "tests.ppos.test_slashing_zero#test_ZB_NP_12", "labels": [{"name": "parentSuite", "value": "tests.ppos"}, {"name": "suite", "value": "test_slashing_zero"}, {"name": "host", "value": "hietel"}, {"name": "thread", "value": "25124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ppos.test_slashing_zero"}]}