{"name": "test_ZB_NP_05", "status": "broken", "statusDetails": {"message": "ValueError: {'code': -32000, 'message': 'the tx data is invalid: the func is not exist'}", "trace": "new_genesis_env = <environment.env.TestEnvironment object at 0x00000269F5964CC0>, client_noconsensus = <tests.lib.client.Client object at 0x00000269F5758828>\n\n    def test_ZB_NP_05(new_genesis_env, client_noconsensus):\n        \"\"\"\n        节点被选中共识验证人查询零出块记录表（存在零出块记录）\n        \"\"\"\n        update_zero_produce(new_genesis_env)\n        economic = client_noconsensus.economic\n        node = economic.env.get_consensus_node_by_index(0)\n        create_pledge_node_information(client_noconsensus)\n        initial_validator, slashing_node_list = gen_validator_list(economic.env.consensus_node_id_list(), client_noconsensus.node.node_id)\n        log.info(\"verifier nodeid list: {}\".format(slashing_node_list))\n>       assert_set_validator_list(node, slashing_node_list)\n\nclient_noconsensus = <tests.lib.client.Client object at 0x00000269F5758828>\neconomic   = <tests.lib.economic.Economic object at 0x00000269F5758DD8>\ninitial_validator = ['488fb1c783f7ac6a20d320e8442ddebe8cf983f5eda7effd00b919afdcf31dcd10e6b2bcee158245fef3a587e0248bea8cf8f6905af833623d03...b2046a77afb48a13f875c17d674421eda9c5345c32d9378490326d628e9f9b60392fcf7832ba82c9ebf5953573d6f93878c24f77e9cb53ee59fec']\nnew_genesis_env = <environment.env.TestEnvironment object at 0x00000269F5964CC0>\nnode       = <environment.node.Node object at 0x00000269F51BE9B0>\nslashing_node_list = ['cfdf43591661d0107b7389a0ef68a2681cdf67d93183e36201acb631920cee349d4c6d7e8557602e101df0fe6b2e6808c66e0a27a2942096348f...0a9bf5bf7c6f5fb2abbeea3546d6557cec02992f7753f99c2e39f87fdbdb6280d7fc8a243518ef27834e55eb03ad6d8ef2f627b8f0001ee185300']\n\ntests\\ppos\\test_Zero_out_penalty.py:201: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\ppos\\test_Zero_out_penalty.py:37: in assert_set_validator_list\n    result = node.debug.setValidatorList(validator_list, pri_key)\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\debug.py:22: in setValidatorList\n    return send_obj_transaction(self, data, self.web3.stakingAddress, pri_key, transaction_cfg)\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\utils\\transactions.py:72: in send_obj_transaction\n    tx_hash = HexBytes(obj.web3.platon.sendRawTransaction(signed_data)).hex()\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\eth.py:300: in sendRawTransaction\n    [raw_transaction],\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <client_sdk_python.manager.RequestManager object at 0x00000269F6C58978>, method = 'platon_sendRawTransaction'\nparams = [HexBytes('0xf9017c018405f5e1008303345094100000000000000000000000000000000000000280b90115f901128382076cb9010bf90108b84...5dbc76520cedeb8259641ed7607644e5c9262134d184dc856ca0214d609bbbaf5399a5a1d20d8adc6e0af168131575d47d0378bd7c9ac8a1bd0f')]\n\n    def request_blocking(self, method, params):\n        \"\"\"\n        Make a synchronous request using the provider\n        \"\"\"\n        response = self._make_request(method, params)\n    \n        if \"error\" in response:\n>           raise ValueError(response[\"error\"])\nE           ValueError: {'code': -32000, 'message': 'the tx data is invalid: the func is not exist'}\n\nmethod     = 'platon_sendRawTransaction'\nparams     = [HexBytes('0xf9017c018405f5e1008303345094100000000000000000000000000000000000000280b90115f901128382076cb9010bf90108b84...5dbc76520cedeb8259641ed7607644e5c9262134d184dc856ca0214d609bbbaf5399a5a1d20d8adc6e0af168131575d47d0378bd7c9ac8a1bd0f')]\nresponse   = {'error': {'code': -32000, 'message': 'the tx data is invalid: the func is not exist'}, 'id': 3, 'jsonrpc': '2.0'}\nself       = <client_sdk_python.manager.RequestManager object at 0x00000269F6C58978>\n\nc:\\users\\hietel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\client_sdk_python\\manager.py:112: ValueError"}, "description": "\n    节点被选中共识验证人查询零出块记录表（存在零出块记录）\n    ", "attachments": [{"name": "env log", "source": "81625449-f98e-4868-a750-c33caeb8929b-attachment.uri", "type": "text/uri-list"}, {"name": "env status", "source": "af8a9732-f3c8-40d0-8afd-1116e1c5bbb8-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "41427b9d-56fb-4c5a-bd0c-5eb9d639b145-attachment.txt", "type": "text/plain"}], "start": 1586610469781, "stop": 1586610573018, "uuid": "d46b0dbd-8958-4f9d-873c-c52ba5ffa5a0", "historyId": "9689b0616fa8851c7f8297cc37b7b2ec", "testCaseId": "6d42c4c5c4622258f710ef8b02735213", "fullName": "tests.ppos.test_Zero_out_penalty#test_ZB_NP_05", "labels": [{"name": "parentSuite", "value": "tests.ppos"}, {"name": "suite", "value": "test_Zero_out_penalty"}, {"name": "host", "value": "hietel"}, {"name": "thread", "value": "25124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ppos.test_Zero_out_penalty"}]}